chat_model:
  init_args:
    model: google/gemini-2.5-flash-lite-preview-09-2025
    model_provider: openai
    api_key: 
    base_url: https://openrouter.ai/api/v1


image_generator:
  class_path: tools.ImageGeneratorFalAPI
  init_args:
    api_key: ""
    model: fal-ai/imagen4/preview/fast


video_generator:
  class_path: tools.VideoGeneratorFalAPI
  init_args:
    api_key: ""
    model: fal-ai/veo3.1/fast/image-to-video


working_dir: .working_dir/idea2video
