chat_model:
  init_args:
    model: google/gemini-2.5-flash-lite-preview-09-2025
    model_provider: openai
    api_key: ""
    base_url: https://openrouter.ai/api/v1


image_generator:
  class_path: tools.ImageGeneratorKieAPI
  init_args:
    api_key: ""
    model: "flux-kontext-pro"


video_generator:
  class_path: tools.VideoGeneratorKieAPI
  init_args:
    api_key: ""
    model: "veo3"


working_dir: .working_dir/script2video
